version: '3'

tasks:
  proto:
    cmds:
      - protoc cmd/pdp_agent/api/v1/*.proto --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative --proto_path=.
  build:
    cmds:
        - go mod download
        - go build -o autenticami ./cmd/pdp_agent
    silent: true
  test:
    cmds:
        - make coverage
    silent: true
