version: '3'

tasks:
  proto:
    cmds:
      - make protoc
  build:
    cmds:
      - make build
    silent: true
  hot:
    cmds:
      - air --build.cmd "go build -o dist/pdpagent ./cmd/pdpagent/main.go" --build.bin "./dist/pdpagent"
  test:
    cmds:
      - make coverage
    silent: true
