version: '3'

tasks:
  proto:
    cmds:
      - protoc cmd/pdpagent/api/v1/*.proto --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative --proto_path=.
  build:
    cmds:
      - go mod download
      - go build -o autenticami ./cmd/pdpagent
    silent: true
  hot:
    cmds:
      - air --build.cmd "go build -o dist/pdpagent ./cmd/pdpagent/main.go" --build.bin "./dist/pdpagent"
  test:
    cmds:
      - make coverage
    silent: true
